language: python

sudo: false

python:
  - "3.7"

# Match postgresql version to that in conf/pillar/project.sls
services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/venvs

env:
  - DJANGO_SETTINGS_MODULE="cc_licenses.settings.dev"

install:
  - pip install -U pip wheel
  - pip install -U -r requirements/dev.txt

before_script:
  - createdb --encoding=UTF-8 cc_licenses --username=postgres --owner=`whoami`
  # Uncomment for Requires.IO pushes of develop and master merges (not pull-request builds)
  # Requires the $REQUIRES_IO_TOKEN environment variable defined at Travis CI for this project
  # See developer documentation section on depdency tracking for more information.
  # - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then requires.io update-branch -t $REQUIRES_IO_TOKEN -r rescueid -n $(echo $TRAVIS_BRANCH | sed "s|/|__|g") . ; fi
  # Uncomment for PostGIS support
  # - psql service_info -c "CREATE EXTENSION postgis;" -U postgres

script:
  - make -j lint test docs
