[tool.black]
# Force exclude is used as pre-commit feeds individual file names based on
# filters
force-exclude = '''
(
    /.local/
    | /node_modules/
    | /venv/
)
'''
line-length = 79
target-version = ['py39', 'py310']


[tool.coverage.run]
branch = true
concurrency = ['multiprocessing']
omit = [
    '*/management/commands/*',
    '*/migrations/*',
    '*/settings/*',
    '*/tests/*',
    '*/urls.py',
    '*/wsgi.py',
    '.direnv/*',
    '.local/*',
    'env/*',
    'fabfile.py',
    'manage.py',
    'venv/*',
]
parallel = true
source = [
    '.',
]

[tool.coverage.report]
fail_under = 98.00
precision = 2
show_missing = true
skip_covered = true
skip_empty = true


# [tool.flake8]
#   config: .flake8
# also see: https://github.com/PyCQA/flake8/issues/234


[tool.isort]
extend_skip = [
    '.cache',
]
import_heading_firstparty = 'First-party/Local'
import_heading_future = 'Future'
import_heading_stdlib = 'Standard library'
import_heading_thirdparty = 'Third-party'
line_length = 79
multi_line_output = 3
no_lines_before = 'LOCALFOLDER'
profile = 'black'


# [tool.pre-commit]
#   config: .pre-commit-config.yaml
